[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'setuptools_scm[toml]>=3.4',
]

[tool.setuptools_scm]
fallback_version = '0.0.15'
local_scheme = 'dirty-tag'
write_to = '_version.py'
